apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-datastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apnimbus: svc-datastore
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_ROOT_USERNAME
          value: example
        - name: PORT
          value: "8118"
        - name: WAIT_HOSTS
          value: svc-database.dev-namespace.svc.cluster.local:27017
        image: cardiacmodelling/ap-nimbus-datastore:0.0.5
        imagePullPolicy: Always
        name: datastore-ctr
        ports:
        - containerPort: 8118
      restartPolicy: Always
