apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-appmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apnimbus: svc-appmanager
    spec:
      containers:
      - env:
        - name: REST_API_URL_DATA
          value: http://svc-datastore.dev-namespace.svc.cluster.local:8118/
        image: cardiacmodelling/ap-nimbus-app-manager:0.0.10
        imagePullPolicy: Always
        name: appmanager-ctr
        ports:
        - containerPort: 8080
      restartPolicy: Always
