#!/bin/bash -e

apiserver=http://127.0.0.1:8081
cluster="dev-cluster"
clusterrolebinding="dev-clusterrolebinding"
context="dev-context"
namespace="dev-namespace"
secret="dev-secret"
serviceaccount="dev-serviceaccount"
user="dev-user"

