#!/bin/bash -e

apiserver=https://127.0.0.1:16443/apportal
cluster="dev-cluster"
clusterrolebinding="dev-clusterrolebinding"
context="dev-context"
namespace="dev-namespace"
secret="dev-secret"
serviceaccount="dev-serviceaccount"
user="dev-user"
