#!/bin/bash -e

#apiserver=http://k8s-master:8080
#cluster="dev-cluster"
#clusterrolebinding="dev-clusterrolebinding"
#context="dev-context"
namespace="dev-namespace"
#secret="dev-secret"
#serviceaccount="dev-serviceaccount"
#user="dev-user"
