node {
  stage('Checkout') {
    checkout scm
  }
  stage('Build') {
    dir('client-direct') {
      sh "docker build --build-arg build_processors=${PROC_COUNT} -t client-direct:jenkinslatest -f Dockerfile ."
    }
  }
}
