apiVersion: v1
kind: Service
metadata:
  labels:
    apnimbus: svc-database
  name: svc-database
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    apnimbus: svc-database
